import { GeneralContext } from '@/generalContext'
import { Textarea } from './ui/textarea'
import { useContext } from 'react'

export function MainContent() {
  const { input, handleInputChange, completion } = useContext(GeneralContext)

  return (
    <div className="flex flex-col flex-1 gap-4">
      <div className="grid grid-rows-2 gap-4 flex-1">
        <Textarea
          className="resize-none p-4 leading-relaxed"
          placeholder="Add the prompt containing the AI instructions"
          value={input}
          onChange={handleInputChange}
        />
        <b id="resultPlaceholder">Result generated by the AI:</b>
        <div className="border-l-4 pl-8" id="result-content">
          {completion}
        </div>
      </div>
    </div>
  )
}
