import { GeneralContext } from '@/generalContext'
import { Textarea } from './ui/textarea'
import { useContext } from 'react'
import { PromptsSelect } from './PromptsSelect'
import { Button } from './ui/button'
import { LoadingSpinner } from './ui/loadingSpinner'
import { Wand2 } from 'lucide-react'
import { ModelSelect } from './ModelSelect'
import { TemperatureSlider } from './TemperatureSlider'

export function MainContent() {
  const { input, handleInputChange, completion, isLoading, handleSubmit } =
    useContext(GeneralContext)

  return (
    <div className="w-full">
      <div className="h-full flex flex-col gap-6">
        <div className="flex gap-4">
          <ModelSelect />

          <TemperatureSlider />
        </div>
        <div className="flex flex-col justify-end h-full gap-6">
          <div
            className="border-l-8 border-gray-200 pl-8 flex-1 h-36"
            id="result-content"
          >
            <b id="resultPlaceholder">Result generated by the AI:</b>
            {completion}
          </div>
          <div className="flex flex-col gap-4 ">
            <form
              onSubmit={handleSubmit}
              className="flex flex-col gap-4 self-bottom flex-1"
            >
              <PromptsSelect />

              <Textarea
                className="resize-none p-4 leading-relaxed flex-1"
                placeholder="Add the prompt containing the AI instructions"
                value={input}
                onChange={handleInputChange}
              />
              <Button
                type="submit"
                className="w-40 self-end"
                disabled={isLoading}
              >
                {isLoading && <LoadingSpinner />}
                {isLoading ? status : `Send`}
                <Wand2 className="w-4 h-4 ml-2" />
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}
