import { Textarea } from './ui/textarea'

export function MainContent() {
  return (
    <div className="flex flex-col flex-1 gap-4">
      <div className="grid grid-rows-2 gap-4 flex-1">
        <Textarea
          className="resize-none p-4 leading-relaxed"
          placeholder="Add the prompt containing the AI instructions"
        />
        <b id="resultPlaceholder">Result generated by the AI:</b>
        <div className="border-l-4 pl-8" id="result-content"></div>
      </div>
      <p className="text-sm text-muted-foreground">
        Reminder: You can use the variable{' '}
        <code className="text-violet-400">{`{transcription}`}</code> in your
        prompt to add the selected video transcription.
      </p>
    </div>
  )
}
